name: Daily Mastodon Post

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 7 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests python-dotenv Mastodon.py

      - name: Run the bot
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        run: python bot.py

      - name: Commit and Push Updated History File
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git pull origin main --rebase || true

          git add history.txt
          git commit -m "Updated history with new word" || echo "No changes to commit"

          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/gdesiato/word-bot.git main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
